/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                                /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                                /* @} */

/*! @name PORTB19 (number 54), D3[4]/LEDRGB_GREEN
  @{ */
#define BOARD_INITPINS_LED_GREEN_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_LED_GREEN_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LED_GREEN_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LED_GREEN_PIN 19U    /*!<@brief PORTB pin index: 19 */
                                            /* @} */

/*! @name PORTA13 (number 33), J2[2]/D8
  @{ */
#define BOARD_INITPINS_DIR1_FGPIO FGPIOA /*!<@brief FGPIO device name: FGPIOA */
#define BOARD_INITPINS_DIR1_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_DIR1_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DIR1_PIN 13U    /*!<@brief PORTA pin index: 13 */
                                       /* @} */

/*! @name PORTC12 (number 69), J2[1]
  @{ */
#define BOARD_INITPINS_STEP1_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_STEP1_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_STEP1_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_STEP1_PIN 12U    /*!<@brief PORTC pin index: 12 */
                                        /* @} */

/*! @name PORTC13 (number 70), J2[3]
  @{ */
#define BOARD_INITPINS_STEP2_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_STEP2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_STEP2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_STEP2_PIN 13U    /*!<@brief PORTC pin index: 13 */
                                        /* @} */

/*! @name PORTD5 (number 78), J2[4]/D9
  @{ */
#define BOARD_INITPINS_DIR2_FGPIO FGPIOD /*!<@brief FGPIO device name: FGPIOD */
#define BOARD_INITPINS_DIR2_GPIO GPIOD /*!<@brief GPIO device name: GPIOD */
#define BOARD_INITPINS_DIR2_PORT PORTD /*!<@brief PORT device name: PORTD */
#define BOARD_INITPINS_DIR2_PIN 5U     /*!<@brief PORTD pin index: 5 */
                                       /* @} */

/*! @name PORTE0 (number 1), J2[18]/D14
  @{ */
#define BOARD_INITPINS_I2C_SDA_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_I2C_SDA_PIN 0U     /*!<@brief PORTE pin index: 0 */
                                          /* @} */

/*! @name PORTE1 (number 2), J2[20]/D15
  @{ */
#define BOARD_INITPINS_I2C_SCL_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_I2C_SCL_PIN 1U     /*!<@brief PORTE pin index: 1 */
                                          /* @} */

/*! @name PORTE5 (number 6), J9[15]
  @{ */
#define BOARD_INITPINS_PERC_01_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_PERC_01_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_PERC_01_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_PERC_01_PIN 5U     /*!<@brief PORTE pin index: 5 */
                                          /* @} */

/*! @name PORTE4 (number 5), J9[13]
  @{ */
#define BOARD_INITPINS_PERC_02_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_PERC_02_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_PERC_02_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_PERC_02_PIN 4U     /*!<@brief PORTE pin index: 4 */
                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
